kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: gvisor-shoot
  namespace: garden-local
spec:
...
  provider:
    workers:
      - name: worker-xyz
...
        cri:
          name: containerd
          containerRuntimes:
            - type: gvisor
# If you need a custom configuration, you can specify additional config flags
#              providerConfig:
#                apiVersion: gvisor.os.extensions.gardener.cloud/v1alpha1
#                kind: GVisorConfiguration
#                configFlags:
#                  net-raw: "true"
#                  nvproxy: "true"
#                  debug: "true"
...

