---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
    - extensions.gardener.cloud
  resources:
    - clusters
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - containerruntimes
  - containerruntimes/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - secrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list 
  - watch 
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - runtime-gvisor-leader-election
  - gardener-extension-heartbeat 
  verbs:
  - get
  - update
  - patch
- apiGroups:
    - resources.gardener.cloud
  resources:
    - managedresources
  verbs:
    - get
    - list
    - create
    - delete
    - watch
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-runtime-gvisor
  labels:
    app.kubernetes.io/name: gardener-extension-runtime-gvisor
    helm.sh/chart: gardener-extension-runtime-gvisor
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-runtime-gvisor
subjects:
- kind: ServiceAccount
  name: gardener-extension-runtime-gvisor
  namespace: {{ .Release.Namespace }}
